// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf48vcF6fvZRELuBYLYq6uhzHhqCclAOk',
    appId: '1:773730159797:web:34fb582b6f7f6b71d482fc',
    messagingSenderId: '773730159797',
    projectId: 'bookly-app-da8d5',
    authDomain: 'bookly-app-da8d5.firebaseapp.com',
    storageBucket: 'bookly-app-da8d5.firebasestorage.app',
    measurementId: 'G-DJ7EZ82TCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHyUYGr31oksCcTuHh6y-M4lq0HBVwBJ4',
    appId: '1:773730159797:android:35edc966fd3355f9d482fc',
    messagingSenderId: '773730159797',
    projectId: 'bookly-app-da8d5',
    storageBucket: 'bookly-app-da8d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNvHXCW8T2MiPLjjbrpriRym35trS6WZw',
    appId: '1:773730159797:ios:7bef7e186892a433d482fc',
    messagingSenderId: '773730159797',
    projectId: 'bookly-app-da8d5',
    storageBucket: 'bookly-app-da8d5.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNvHXCW8T2MiPLjjbrpriRym35trS6WZw',
    appId: '1:773730159797:ios:7bef7e186892a433d482fc',
    messagingSenderId: '773730159797',
    projectId: 'bookly-app-da8d5',
    storageBucket: 'bookly-app-da8d5.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf48vcF6fvZRELuBYLYq6uhzHhqCclAOk',
    appId: '1:773730159797:web:5dc01e9082193fe4d482fc',
    messagingSenderId: '773730159797',
    projectId: 'bookly-app-da8d5',
    authDomain: 'bookly-app-da8d5.firebaseapp.com',
    storageBucket: 'bookly-app-da8d5.firebasestorage.app',
    measurementId: 'G-8K4F1NLHHD',
  );
}
